blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name= 'all_blogs' ),
    path('<int:blog_id>/', views.detail, name= 'detail' ),
]

personal_portofolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portofolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home' ),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    discription = models.TextField()
    date = models.DateField()
    # image = models.ImageField(upload_to="blog/images/")
    
# 以下はadminページでの表示を変更するコード
    def __str__(self):
        return self.title

portofolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to="portofolio/images/")
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by("-date")
    # blogs = Blog.objects.all()
    return render(request, 'blog/blog.html', {'blogs':blogs})
# Create your views here.

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portofolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portofolio/home.html', {'projects':projects})

blog/templates/blog/blog.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Study Memo</title>
  </head>
  <body>

        
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
          <img src="{% static 'portofolio/trimg.PNG' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
        <a class="navbar-brand" href="#">Achuchuchu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                About
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><a class="dropdown-item" href="#">Who is Achuchuchu?</a></li>
                <li><a class="dropdown-item" href= "{% url 'blog:all_blogs' %}">Study memo</a></li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Projects
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="#">Project 1</a></li>
                  <li><a class="dropdown-item" href="#">Project 2</a></li>
                  <li><a class="dropdown-item" href="#">Project 3</a></li>
                  <li><a class="dropdown-item" href="#">Project 4</a></li>
                </ul>
              </li>
            </ul>
            <a href="{% static 'portofolio/sample.pdf' %}">
              <button  type="button" class="btn btn-info">Info</button>
          </a>
            
        </div>
      </div>
    </nav>
    <h1>Welcome to my Brain page</h1>
    {% for blog in blogs%}
    <div class="card">
      <div class="card-header">
        <h4>{{blog.title}}</h4>
      </div>
      <div class="card-body">
        <p class="card-text">{{blog.date | date:'M d Y'}}</p>
        <p class="card-text"> {{blog.discription |striptags| truncatechars:100 }}</p>
        <a href="{% url 'blog:detail' blog.id %}" class="btn btn-primary">Click!</a>
      </div>
    </div>
    
    <!-- <h2>Achuchuchu has written {{ blogs.count }} blog{{ blogs.count|pluralize}}</h2> -->

    {{blog.image}}
    {% endfor %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/detail.html
<h2>{{ blog.title }}</h2>
<h2>▶︎{{ blog.date|date:'F jS Y'}}◀︎</h2>
<br>
{{ blog.discription|safe }}

portofolio/templates/portofolio/home.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel= "stylesheet" href="{% static 'portofolio/custom.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Pacifico&display=swap" rel="stylesheet">

    <title>Achuchuchu's page</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <img src="{% static 'portofolio/trimg.PNG' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
          <a class="navbar-brand" href="#">Achuchuchu</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  About
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="#">Who is Achuchuchu?</a></li>
                  <li><a class="dropdown-item" href= "{% url 'blog:all_blogs' %}">Study memo</a></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Projects
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="#">Project 1</a></li>
                    <li><a class="dropdown-item" href="#">Project 2</a></li>
                    <li><a class="dropdown-item" href="#">Project 3</a></li>
                    <li><a class="dropdown-item" href="#">Project 4</a></li>
                  </ul>
                </li>
              </ul>
              <a href="{% static 'portofolio/sample.pdf' %}">
                <button  type="button" class="btn btn-info">Info</button>
            </a>
              
          </div>
        </div>
      </nav>
    <h1>Achoo's Portofolio</h1>
    
    <!-- <img src="{% static 'portofolio/a.jpg' %}"> -->
    <!-- <a href= "{% url 'blog:all_blogs' %}">Blog</a> -->
    <!-- <br> -->
    <!-- <a href="{% static 'portofolio/test.pdf' %}">Test PDF</a> -->
    <!-- {% for project in projects %}
    {{project.title}}
    {{project.discription}}
    <br>
    <img src="{{project.image.url}}" height="200">
    <br>
    {% if project.url %}
    <a href="{{project.url}}">Link</a>
    {% endif %}
    {% endfor %} -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>